<a href="https://colab.research.google.com/github/tessasaporito/ds2002-fce6sy/blob/main/API_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import requests
import pandas as pd
import json

#1
api_key = "x"
stock = input()

#2
url = "https://yfapi.net/v6/finance/quote"
querystring = {"symbols": stock}
headers = {
    'x-api-key': api_key
}

response = requests.get(url, headers=headers, params=querystring)


if response.status_code == 200:
    print("API request successful!")
else:
    print(f"Failed to retrieve data: {response.status_code}")


stock_data = response.json()

if not stock_data['quoteResponse']['result']:
    print(f"Stock symbol '{stock}' not found!")
else:
    stock_info = stock_data['quoteResponse']['result'][0]
    print(f"Ticker: {stock}:")
    print(f"Full Name: {stock_info.get('longName')}")
    print(f"Current Market Price: ${stock_info.get('regularMarketPrice')}")
    print(f"52 Week High: ${stock_info.get('fiftyTwoWeekHigh')}")
    print(f"52 Week Low: ${stock_info.get('fiftyTwoWeekLow')}")

#top 5 trending
url_trending = "https://yfapi.net/v1/finance/trending/us"

response_trending = requests.get(url_trending, headers=headers)

if response_trending.status_code == 200:

    trending_data = response_trending.json()
    trending_stocks = [stock.get('symbol', 'N/A') for stock in trending_data['finance']['result'][0]['quotes'][:5]]
    print("\nTrending Stocks:")
    for stock in trending_stocks:
        print(stock)
else:
    print(f"Failed to retrieve trending stocks: {response_trending.status_code}")

smci
API request successful!
Ticker: smci:
Full Name: Super Micro Computer, Inc.
Current Market Price: $402.4
52 Week High: $1229.0
52 Week Low: $226.59

Trending Stocks:
COST
SMCI
BABA
PYPL
NU

In [74]:
#3
df = pd.DataFrame([{
    'Ticker': stock,
    'Full Name': stock_info.get('longName', 'N/A'),
    'Current Market Price': stock_info.get('regularMarketPrice', 'N/A'),
    '52 Week High': stock_info.get('fiftyTwoWeekHigh', 'N/A'),
    '52 Week Low': stock_info.get('fiftyTwoWeekLow', 'N/A')
    }])

df.to_csv(f"{stock}_stock_data.csv")

df.head()

,Ticker,Full Name,Current Market Price,52 Week High,52 Week Low
0,NU,"Super Micro Computer, Inc.",402.4,1229.0,226.59