<a href="https://colab.research.google.com/github/tessasaporito/ds2002-fce6sy/blob/main/Project%201/Data_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#imports

import json
import csv
import pandas as pd
import sqlite3
import pymysql
import mysql.connector
from sqlalchemy import create_engine

In [ ]:
#convert function

#convert to csv file
def to_csv(df, csv_file):
    df.to_csv(csv_file, index=False)
    print(f"Data successfully saved to CSV file")

#convert to json file
def to_json(df, json_file):
    df.to_json(json_file, orient='records', lines=False, indent=4)
    print(f"Data successfully saved to JSON file")

#convert to sqlite database
def to_sql(df, table_name, db_file):
    connection = sqlite3.connect(db_file)
    df.to_sql(table_name, connection, if_exists='replace', index=False)
    connection.close()
    print(f"Data successfully saved to SQLite")

#convert function
def convert():
    df_name = input("Name of dataframe: ")
    try:
        df = eval(df_name)
        if not isinstance(df, pd.DataFrame):
            print(f"{df_name} is not a dataframe")
            return
    except NameError:
        print(f"{df_name} not found.")
        return
    except Exception as e:
        print(f"An error occurred: {e}")
        return
    try:
        target_type = input("Convert into (csv, json, or sql): ")
    except:
        print("Invalid input")
        return
    if target_type == 'csv':
        output_file = input("Output CSV file name: ")
        to_csv(df, output_file)
    elif target_type == 'json':
        output_file = input("Output JSON file name: ")
        to_json(df, output_file)
    elif target_type == 'sql':
        table_name = input("Table name: ")
        db_file = input("Database name: ")
        to_sql(df, table_name, db_file)
    else:
        print("Conversion failed")

In [ ]:
#store

def store():
    df_name = input("Name of dataframe: ")
    try:
        df = eval(df_name)
        if not isinstance(df, pd.DataFrame):
            print(f"{df_name} is not a dataframe.")
            return
    except NameError:
        print(f"{df_name} not found.")
        return
    except Exception as e:
        print(f"An error occurred: {e}")
        return
    db_file = input("Database name: ")
    table_name = input("Table name: ")
    try:
        connection = sqlite3.connect(db_file)
        df.to_sql(table_name, connection, if_exists='replace', index=False)
        connection.close()
        print(f"Data successfully saved to SQLite database in table '{table_name}'")
    except Exception as e:
        print(f"Storage failed")

CSV: Connecticut School Attendance by Student Group and District, 2021-2022

File name: School_Attendance_by_Student_Group_and_District__2021-2022.csv

File in my GitHub Repo, sourced from Data.gov

In [ ]:
#fetch

#put csv in df
attendance = pd.read_csv('/School_Attendance_by_Student_Group_and_District__2021-2022.csv')

attendance.head()

,District code,District name,Category,Student group,2021-2022 student count - year to date,2021-2022 attendance rate - year to date,2020-2021 student count,2020-2021 attendance rate,2019-2020 student count,2019-2020 attendance rate,Reporting period,Date update
0,00000CT,Connecticut,NaN,All Students,500285,91.69,496092.0,92.94,508346.0,94.79,June 2022,07/22/2022
1,00000CT,Connecticut,Homelessness,Students Experiencing Homelessness,1814,83.48,1735.0,81.55,3916.0,88.84,June 2022,07/22/2022
2,00000CT,Connecticut,Students With Disabilities,Students With Disabilities,78417,88.99,76487.0,89.46,80365.0,92.77,June 2022,07/22/2022
3,00000CT,Connecticut,Free/Reduced Lunch,Free Meal Eligible,168984,88.51,176225.0,88.61,193706.0,93.14,June 2022,07/22/2022
4,00000CT,Connecticut,Free/Reduced Lunch,Reduced Price Meal Eligible,29905,91.84,30886.0,92.99,27507.0,95.18,June 2022,07/22/2022

In [ ]:
#initial number of columns
print("Number of columns: " + str(attendance.shape[1]))

#initial number of records
print("Number of records: " + str(attendance.shape[0]))

Number of columns: 12
Number of records: 2019

In [ ]:
#modify

#make columns numeric
attendance['2021-2022 attendance rate - year to date'] = pd.to_numeric(attendance['2021-2022 attendance rate - year to date'], errors='coerce')
attendance['2020-2021 attendance rate'] = pd.to_numeric(attendance['2020-2021 attendance rate'], errors='coerce')
attendance['2019-2020 attendance rate'] = pd.to_numeric(attendance['2019-2020 attendance rate'], errors='coerce')

#drop "Reporting period" and "Date update" columns
attendance = attendance.drop(columns=['Reporting period', 'Date update'])

#add new column "Average Attendance Rate 2019-2022"
attendance['2019-2022 average attendance rate'] = attendance[['2021-2022 attendance rate - year to date', '2020-2021 attendance rate', '2019-2020 attendance rate']].mean(axis=1).round(2)

attendance.head()

,District code,District name,Category,Student group,2021-2022 student count - year to date,2021-2022 attendance rate - year to date,2020-2021 student count,2020-2021 attendance rate,2019-2020 student count,2019-2020 attendance rate,2019-2022 average attendance rate
0,00000CT,Connecticut,NaN,All Students,500285,91.69,496092.0,92.94,508346.0,94.79,93.14
1,00000CT,Connecticut,Homelessness,Students Experiencing Homelessness,1814,83.48,1735.0,81.55,3916.0,88.84,84.62
2,00000CT,Connecticut,Students With Disabilities,Students With Disabilities,78417,88.99,76487.0,89.46,80365.0,92.77,90.41
3,00000CT,Connecticut,Free/Reduced Lunch,Free Meal Eligible,168984,88.51,176225.0,88.61,193706.0,93.14,90.09
4,00000CT,Connecticut,Free/Reduced Lunch,Reduced Price Meal Eligible,29905,91.84,30886.0,92.99,27507.0,95.18,93.34

In [ ]:
#post processing number of columns
print("Number of columns: " + str(attendance.shape[1]))

#post processing number of records
print("Number of records: " + str(attendance.shape[0]))

Number of columns: 11
Number of records: 2019

In [ ]:
#call convert function

convert()

Name of dataframe: attendance
Convert into (csv, json, or sql): json
Output JSON file name: attendance json
Data successfully saved to JSON file

In [ ]:
#call store function

store()

Name of dataframe: attendance
Database name: attendance db
Table name: attendance
Data successfully saved to SQLite database in table 'attendance'

JSON file

File name: School_Dropout_Rates_in_Iowa__State-wide_and_by_Subgroup.json

File in my GitHub Repo, sourced from Data.gov

In [ ]:
#fetch

#put json into df
dropouts = pd.read_json('/School_Dropout_Rates_in_Iowa.json')

dropouts.head()

,Report Period Start,Report Period End,Group/Subgroup,Dropouts,Enrollments,Rate
0,10/01/2016,09/30/2017,State Total,4264,220954,1.93
1,10/01/2016,09/30/2017,Individualized Education Program,908,27772,3.27
2,10/01/2016,09/30/2017,Free or Reduced Lunch,3165,84480,3.75
3,10/01/2016,09/30/2017,English Language Learners,366,8953,4.09
4,10/01/2016,09/30/2017,African American,626,12705,4.93

In [ ]:
#initial number of columns
print("Number of columns: " + str(dropouts.shape[1]))

#initial number of records
print("Number of records: " + str(dropouts.shape[0]))

Number of columns: 6
Number of records: 52

In [ ]:
#modify

#add a column for high/low/average dropout rate (Low: 0 to <1.5, Average: 1.5 to <2.5, High: above 2.5)
def rate_level(rate):
    if rate < 1.5:
        return 'Low'
    elif rate < 2.5:
        return 'Average'
    else:
        return 'High'

dropouts['Level'] = dropouts['Rate'].apply(rate_level)

#Create a Fiscal Year Column based on the Report Period End Column(since all are Oct 1 - Sept 30)
dropouts['Report Period End'] = pd.to_datetime(dropouts['Report Period End'])
dropouts['Fiscal Year'] = dropouts['Report Period End'].dt.year

#drop Report Period Start and Report Period End columns
dropouts = dropouts.drop(columns=['Report Period Start', 'Report Period End'])

dropouts.head()

,Group/Subgroup,Dropouts,Enrollments,Rate,Level,Fiscal Year
0,State Total,4264,220954,1.93,Average,2017
1,Individualized Education Program,908,27772,3.27,High,2017
2,Free or Reduced Lunch,3165,84480,3.75,High,2017
3,English Language Learners,366,8953,4.09,High,2017
4,African American,626,12705,4.93,High,2017

In [ ]:
#post processing number of columns
print("Number of columns: " + str(dropouts.shape[1]))

#post processing of records
print("Number of records: " + str(dropouts.shape[0]))

Number of columns: 6
Number of records: 52

In [ ]:
#call convert function

convert()

Name of dataframe: dropouts
Convert into (csv, json, or sql): csv
Output CSV file name: dropouts csv
Data successfully saved to CSV file

In [ ]:
#call store function

store()

Name of dataframe: dropouts
Database name: dropouts db
Table name: dropouts
Data successfully saved to SQLite database in table 'dropouts'